# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       [ ROLE_OWNER, ROLE_USER ]
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt|trans)|css|images|js|compiled/(js|css))/
            security: false

        main:
            pattern: ^/
            form_login:
                provider:                       fos_userbundle
                csrf_token_generator:           security.csrf.token_manager
                login_path:                     /ingreso
                check_path:                     /comprobar-ingreso
            logout:
                path:                           /salir
                target:                         /
            anonymous:                          true

    access_control:
        - { path: ^/ingreso, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }
        - { path: ^/usuarios/, role: ROLE_ADMIN }
