# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.form.passing_place:
        class: AppBundle\Form\Type\ReservaPassingPlaceType
        arguments: [ '@doctrine.orm.entity_manager' ]
        tags:
            - { name: form.type }
    app.form.type.reserva_type:
        class: AppBundle\Form\Type\ReservaType
        arguments: [ '@doctrine.orm.entity_manager' ]
        tags:
            - { name: form.type }
    app.form.type.place_type:
        class: AppBundle\Form\Type\PlaceType
        arguments: [ '@doctrine.orm.entity_manager' ]
        tags:
            - { name: form.type }
    app.form.type.user_type:
        class: AppBundle\Form\Type\UserType
        arguments: [ '@security.token_storage' ]
        tags:
            - { name: form.type }
    app.form.type.invoice_form_type:
        class: AppBundle\Form\Type\InvoiceFormType
        arguments: [ '@doctrine.orm.entity_manager' ]
        tags:
            - { name: form.type }
    app.form.type.invoice_line_form_type:
        class: AppBundle\Form\Type\InvoiceLineType
        arguments: [ '@doctrine.orm.entity_manager' ]
        tags:
            - { name: form.type }
    app.form.type.reserva_filter_form_type:
        class: AppBundle\Form\Type\ReservaFilterFormType
        arguments: [ '@doctrine.orm.entity_manager' ]
        tags:
            - { name: form.type }
    app.form.type.reserva_assigned_filter_type:
        class: AppBundle\Form\Type\ReservaAssignedFilterType
        arguments: [ '@doctrine.orm.entity_manager' ]
        tags:
            - { name: form.type }
    app.form.type.cobro_filter_form_type:
        class: AppBundle\Form\Type\CobroFilterFormType
        arguments: [ '@doctrine.orm.entity_manager' ]
        tags:
            - { name: form.type }
    app.form.type.pay_filter_form_type:
        class: AppBundle\Form\Type\PayFilterFormType
        arguments: [ '@doctrine.orm.entity_manager' ]
        tags:
            - { name: form.type }

    app.morris_graph.area:
        class: AppBundle\Services\MorrisGraphGenerator
        arguments: [ '@doctrine.orm.entity_manager' ]

    app.form.profile:
        class: AppBundle\Form\Type\ProfileType
        tags:
            - { name: form.type, alias: user_profile }

    app.profile.listener:
        class: AppBundle\Listener\ProfileListener
        arguments: [ '@router' ]
        tags:
            - { name: kernel.event_subscriber }
    app.listener.response_cache_listener:
        class: AppBundle\Listener\AddResponseCacheListener
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
            - name: twig.extension
